name: Cypress Test
# Definir cuando se va a ejecutar esta action.
on: [push]
# Necesitamos indicar que realizará
jobs:
  cypress-run:
    # Necesitamos indicar en que maquina hara las pruebas.
    runs-on: ubuntu-latest
    # Indicamos que pasos haremos para poder realizar las pruebas.
    steps:
    # vamos a llamar al action Checkout: Este action se va a encargar de poder clonar nuestro proyecto en la maquina virtual.
    - name: Checkout
      uses: actions/checkout@v3.0.0
    # despues de clonar nuestro proyecto vamos a usar el action de cypress para poder ejecutar los test.
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
    # Luego de indicar que usaremos cypress vamos a decir que ejecute el comando npm start
      with:
        start: npm start
